Restart smwingsd on failure
NethServer/nethserver-httpd-admin pull request #27
Opened 2018-04-14 18:55 UTC by stephdl

2018-04-15 07:46 UTC, DavidePrincipi reviewed
If the failure is permanent does it try forever or gives up after some attempts?

2018-04-15 16:48 UTC, stephdl commented
https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=

 the doc states 

> Setting this to on-failure is the recommended choice for long-running services, in order to increase reliability by attempting automatic recovery from errors.

I have no informations that the restart action stops after a number of attempts

2018-04-15 17:27 UTC, DavidePrincipi commented
Yes now I found them from your link:

> Note that service restart is subject to unit start rate limiting configured with StartLimitIntervalSec= and StartLimitBurst=, see systemd.unit(5) for details. A restarted service enters the failed state only after the start limits are reached.

3 failed starts in 20 seconds could be reasonable...

2018-04-15 17:35 UTC, stephdl commented
oups you right :')

2018-04-15 19:30 UTC, DavidePrincipi approved these changes

2018-04-15 19:32 UTC, DavidePrincipi requested changes

2018-04-15 19:32 UTC, DavidePrincipi commented on root/usr/lib/systemd/system/smwingsd.service
> +StartLimitBurst=3
Move to [unit] section?

2018-04-16 07:52 UTC, stephdl commented on root/usr/lib/systemd/system/smwingsd.service
> +StartLimitBurst=3
yes, seems so, let me check

2018-04-16 12:22 UTC, DavidePrincipi approved these changes
As @stephdl pointed out, the docs do not refer to our systemd version, 219. `StartLimitBurst` and `StartLimitInterval` were moved to `[Unit]`, but are still acceptable under `[Service]` too.

https://lists.freedesktop.org/archives/systemd-devel/2017-July/039255.html

2018-04-16 12:22 UTC, merged